server:
  port: 1800
spring:
  application:
    name: restfulapi
  datasource:
    password: pass
    url: jdbc:postgresql://localhost:5432/restfulapi-mall
    username: postgres
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: postgres